### ISSUE TITLE
Удалить столбцы 'бизнес-процесс', 'наименование', 'комментарии'

### ISSUE THREAD

**Issue by compartia** [nemoware/gpn-analyse-ui#10]
#4 
@LitJane если согласна, переведи на @IvanKrivosh

**Comment by LitJane** [comment]
Столпы таблиц
Я удалять без устали согласна
Покуда нет на Свете разума такого,
Кому под силу объяснить 
Зачем, кому, столпы предназначались

(Стих не мой, я просто дала согласие!)
