### ISSUE TITLE
Нарушения: Убирать документ из закладки, если нарушение было исправлено

### ISSUE THREAD

**Issue by LitJane** [nemoware/gpn-analyse-ui#102]
В частности, если был добавлен отсутствующий атрибут.
Связанное замечание (кмк):  https://github.com/nemoware/gpn-analyse-ui/issues/73

**Comment by eliseysinkevich** [comment]
Сделал обработку для даты и номера. С остальными предупреждениями/нарушениями пока проблематично

**Comment by LitJane** [comment]
Для документа был добавлен атрибут "Дата" , но из закладки "Нарушения" он никуда не делся.
![image](https://user-images.githubusercontent.com/55797683/83027855-55b92b00-a039-11ea-8dc5-0163e52c3d6f.png)
![image](https://user-images.githubusercontent.com/55797683/83028008-87ca8d00-a039-11ea-9182-d63d662d2d13.png)
![image](https://user-images.githubusercontent.com/55797683/83027913-68cbfb00-a039-11ea-9868-61a9fac98468.png)

**Comment by compartia** [comment]
@LitJane нет ли секретной информации на этих скриншотах? (они видны всему миру)

**Comment by compartia** [comment]
@LitJane скриншоты удалил

**Comment by eliseysinkevich** [comment]
Подскажите, пожалуйста, какой тип документа (проверил сейчас на протоколе - все хорошо, нарушение исчезает)
И еще вопрос - при добавлении атрибута в документ  у меня аудит поменял статус на "В работе", вследствие чего вкладка "Нарушения" стала неактивной - так и должно быть?

**Comment by Selgis** [comment]
Добрый день! При добавлении в договор атрибута "дата" нарушение не исчезло.

**Comment by vanyasav** [comment]
Что из этого еще актуально?(коды предупреждений взяты из анализатора)


  org_name_not_found = 1
  org_type_not_found = 2
  org_struct_level_not_found = 3
  date_not_found = 4
  number_not_found = 5
  # 6? what about 6
  value_section_not_found = 7
  contract_value_not_found = 8
  subject_section_not_found = 6  # here it is
  contract_subject_not_found = 9

  protocol_agenda_not_found = 10

  boring_agenda_questions = 11
  contract_subject_section_not_found = 12

  doc_too_big = 13

 @compartia
