### ISSUE TITLE
админ не может быть одновременно и аудитором

### ISSUE THREAD

**Issue by SergeyShalaevsky** [nemoware/gpn-analyse-ui#104]
выдержка из тз, то что может делать юзер с правами админа:
1.	Мониторинг событий;
2.	Управление правами доступа пользователя;
3.	Доступа к данным не будет иметь

**Comment by IvanKrivosh** [comment]
![image](https://user-images.githubusercontent.com/52923077/73167997-01914f00-410a-11ea-98c8-ea523b2e65ea.png)
![image](https://user-images.githubusercontent.com/52923077/73168017-0ce47a80-410a-11ea-878f-08c1eb055266.png)
