### ISSUE TITLE
Нет возможности отредактировать ограничение

### ISSUE THREAD

**Issue by LitJane** [nemoware/gpn-analyse-ui#105]
Нет возможности отредактировать/удалить ограничение Устава (см. пункт  номер 30) 
**ФАЙЛ**
_ООО Савицкий_Устав.doc_

![image](https://user-images.githubusercontent.com/55797683/74018998-ee06a380-49a7-11ea-8b3b-ac4356bc6f21.png)

**Comment by IvanKrivosh** [comment]
@SergeyShalaevsky нужен json для проверки корректной разметки теста.

**Comment by SergeyShalaevsky** [comment]
[5e3140dc2a5a4e5693b60c1b.txt](https://github.com/nemoware/gpn-analyse-ui/files/4170111/5e3140dc2a5a4e5693b60c1b.txt)

**Comment by IvanKrivosh** [comment]
@LitJane нужно больше конкретики
![image](https://user-images.githubusercontent.com/52923077/74021673-00cfa700-49ad-11ea-8a6a-99609efeed74.png)
