### ISSUE TITLE
Предусмотреть возможность ввода значений при редактировании ограничения/предмета договора

### ISSUE THREAD

**Issue by LitJane** [nemoware/gpn-analyse-ui#107]
Предусмотреть возможность ввода значений, помимо выбора из списка, при редактировании ограничения устава  и предмета договора.

**Comment by IvanKrivosh** [comment]
@LitJane ограничения и предмет договора - есть справочник значений, которые могут быть получены анализатором. Если предмет договор - есть значение атрибута, и его можно спокойно подменить, то ограничение устава - есть сам атрибут, и добавление новых (произвольных) атрибутов видится маловероятных

**Comment by LitJane** [comment]
Речь не про добавление новых атрибутов, а про возможность не листать весь список, а находить нужный атрибут по  введенному буквосочетанию

**Comment by compartia** [comment]
combobox что ли?

**Comment by IvanKrivosh** [comment]
![image](https://user-images.githubusercontent.com/52923077/75675992-686dcf00-5c99-11ea-9173-5c3a8b520ff0.png)
![image](https://user-images.githubusercontent.com/52923077/75676066-8c311500-5c99-11ea-81e5-ab7ef063119e.png)
Поиск доступен всегда при выборе атрибута и его значение, если он из справочника.
