### ISSUE TITLE
Отображать ограничения в графике в соответствии с их порядком в Уставе

### ISSUE THREAD

**Issue by LitJane** [nemoware/gpn-analyse-ui#108]
_Замечание зафиксировано, но предлагаю эту конкретную реализацию оставить на  потом. :)_ 

А вот сейчас можно отображать их хотя бы в алфавитном порядке, возможно это проще и тоже вполне устроит БЗ.

**Comment by IvanKrivosh** [comment]
![image](https://user-images.githubusercontent.com/52923077/75444663-e87ff600-5974-11ea-8738-2b6f37a438a2.png)
![image](https://user-images.githubusercontent.com/52923077/75444727-08afb500-5975-11ea-90df-098ef1373133.png)
