### ISSUE TITLE
Добавить разрядность в отображении сумм

### ISSUE THREAD

**Issue by LitJane** [nemoware/gpn-analyse-ui#109]
Добавить разрядность в отображении сумм в тексте документов.

**Comment by thingumajig** [comment]
Крайне желательно это сделать к 13!

**Comment by IvanKrivosh** [comment]
![image](https://user-images.githubusercontent.com/52923077/74246089-06065c00-4cf5-11ea-961d-e0356329a34b.png)
1. Если форматировать текст по найденным атрибутам, но не все сумму будут отформатированы
2. Если форматировать текст при первичном расставлении слов, т.е. проверять является ли слово числом, то сюда попадут и все остальные числа, которые не являются суммами

**Comment by IvanKrivosh** [comment]
Реализован вариант №1.

**Comment by IvanKrivosh** [comment]
@LitJane просьба прокомментировать, какой из вариантов все верный.

**Comment by thingumajig** [comment]
Может быть выбирать числа для всех подстрок, отобранных следующим регэкспом(что-то типа, в первом приближении)
` (\d+([\.\, ]\d+)*).{0,25}(руб|доллар|евро|тенге)`
А затем в его соответствующей capture group выставлять разрядность?

**Comment by thingumajig** [comment]
смысл в том, что дополнительный контекст вблизи в виде руб|дол|тенге|евро неплохо исключает _вероятность_ зацепить номера договоров (и других длинных последовательностей чисел).

**Comment by IvanKrivosh** [comment]
![image](https://user-images.githubusercontent.com/52923077/75680993-bb4c8400-5ca3-11ea-9d52-73a0160e4804.png)
