### ISSUE TITLE
Аpp is stuck after adding an audit + too many pink balloons

### ISSUE THREAD

**Issue by compartia** [nemoware/gpn-analyse-ui#11]
<img width="673" alt="Capture d’écran 2019-10-01 à 00 00 37" src="https://user-images.githubusercontent.com/7677437/65895851-a14e0300-e3de-11e9-94d5-23d51abfb630.png">
<img width="869" alt="Capture d’écran 2019-09-30 à 23 58 04" src="https://user-images.githubusercontent.com/7677437/65895854-a1e69980-e3de-11e9-880c-2fdff6d97f7a.png">

**Comment by IvanKrivosh** [comment]
element.statuses[0].status.name -  проблема в структуре БД.

**Comment by IvanKrivosh** [comment]
Предлагаю в readme описать все коллекции, которые необходимы для корректной работы приложения.

**Comment by eliseysinkevich** [comment]
Статические данные, такие как статусы, будут добавляться при старте приложения (в случае их отсутствия)

**Comment by compartia** [comment]
> Предлагаю в readme описать все коллекции, которые необходимы для корректной работы приложения.

@IvanKrivosh  можно в репозиторий положить json с начальной структурой, а в ридми --  ссылку на него

**Comment by eliseysinkevich** [comment]
@compartia А зачем? Я же предложил создавать все необходимые данные просто при старте сервера. Это проще, чем вручную заливать в базу json из репозитория

**Comment by compartia** [comment]
@eliseysinkevich можно и так, да. (Просто мне кажется противоестественным писать код в ридми)
