### ISSUE TITLE
Объясните сакральный смысл этой страницы :)

### ISSUE THREAD

**Issue by LitJane** [nemoware/gpn-analyse-ui#111]
Адрес: http://192.168.10.36:3000/#/settings 

![image](https://user-images.githubusercontent.com/55797683/75235281-07dc1f00-57cd-11ea-9cae-33ae22ccf3ce.png)

**Comment by IvanKrivosh** [comment]
Данная страница была в первоначальном проекте. Видимо, предполагалось, что юзер сможет что-то настраивать под себя. Если это не требуется, мы ее уберем.
