### ISSUE TITLE
Брать список ДО из монги

### ISSUE THREAD

**Issue by SergeyShalaevsky** [nemoware/gpn-analyse-ui#112]
Вместо двух источников со списками ДО надо сделать один. При старте анализатор будет обновлять этот список в базе. Гуй будет работать не со своим списком, а взятым из базы. Это надо сделать до 28.02.2020

**Comment by thingumajig** [comment]
@SergeyShalaevsky простите за спам, хочу просто проверить эту настройку

**Comment by thingumajig** [comment]
@thingumajig

**Comment by compartia** [comment]
<img width="508" alt="Capture d’écran 2020-02-27 à 16 46 35" src="https://user-images.githubusercontent.com/7677437/75427064-cab88e00-5980-11ea-8c7c-58e46da6b6f1.png">
@thingumajig лет ми хелп ю

**Comment by compartia** [comment]
<img width="539" alt="Capture d’écran 2020-02-27 à 17 27 25" src="https://user-images.githubusercontent.com/7677437/75430577-787a6b80-5986-11ea-806d-b11e2fddd6b0.png">
<img width="727" alt="Capture d’écran 2020-02-27 à 17 27 01" src="https://user-images.githubusercontent.com/7677437/75430584-7ca68900-5986-11ea-8634-73f688211bfb.png">


@SergeyShalaevsky бери себе в `violations` ветку `subsidiaries` https://github.com/nemoware/analyser/tree/subsidiaries/analyser

**Comment by compartia** [comment]
@SergeyShalaevsky
я положил их в коллецию `gpn.dictionaries.Subsidiary.values`

**Comment by eliseysinkevich** [comment]
есть небольшая проблемка.. связанная с тем, что коллекцию dictionaries мы довольно давно не используем, поэтому на сервере ее больше нет. можно ли переложить субсидари в отдельную коллекцию?

**Comment by compartia** [comment]
@eliseysinkevich Да, разумеется.
Если это упростит жизнь сильно.
С другой стороны, "отдельную коллекцию" вы тоже пока не используете.
Как удобнее, так и положу.

**Comment by eliseysinkevich** [comment]
удобнее было бы положить все в коллекцию subsidiaries (на мой взгляд).. спасибо!

**Comment by compartia** [comment]
> удобнее было бы положить все в коллекцию subsidiaries (на мой взгляд).. спасибо!

да будет так
(см картинку)
done

<img width="921" alt="Capture d’écran 2020-02-27 à 19 39 35" src="https://user-images.githubusercontent.com/7677437/75441931-7cfc4f80-5999-11ea-9bdc-76a06e3b78a1.png">
