### ISSUE TITLE
Изменить формулировку статуса, ели документ не был проанализирован

### ISSUE THREAD

**Issue by LitJane** [nemoware/gpn-analyse-ui#113]
Заменить на: "Документ не попадает под параметры Аудита"

![image](https://user-images.githubusercontent.com/55797683/75446995-81b10b80-5979-11ea-9ae4-ea58e90d0344.png)

**Comment by compartia** [comment]
не влезет

**Comment by LitJane** [comment]
впихнуть

**Comment by IvanKrivosh** [comment]
@LitJane 
![image](https://user-images.githubusercontent.com/52923077/75659252-b6270f00-5c7a-11ea-8142-70fcebfa35ef.png)
Пойдет?
