### ISSUE TITLE
некоторые атрибуты нельзя редактировать

### ISSUE THREAD

**Issue by SergeyShalaevsky** [nemoware/gpn-analyse-ui#114]
![image](https://user-images.githubusercontent.com/51235093/75344721-44327c80-58ac-11ea-8096-3a79b9bf7fd1.png)
на ui выглядит так.
![image](https://user-images.githubusercontent.com/51235093/75344829-793ecf00-58ac-11ea-8356-4cce540fd71b.png)
проблема в базе, по словам Ивана, выглядит так
документ https://drive.google.com/open?id=1LS7uOJzFh6JTks3tIyot4rFMMqNwNFuc

**Comment by IvanKrivosh** [comment]
![image](https://user-images.githubusercontent.com/52923077/75660286-94c72280-5c7c-11ea-87ed-1c904ecc85a8.png)
![image](https://user-images.githubusercontent.com/52923077/75660341-ac9ea680-5c7c-11ea-9bd7-79d21c335ed1.png)
Не известный атрибут теперь можно заменить/удалить. Так же изменил формулировку.

**Comment by IvanKrivosh** [comment]
Fix: 
![image](https://user-images.githubusercontent.com/52923077/75661015-98a77480-5c7d-11ea-800b-666621fbe5e7.png)
