### ISSUE TITLE
В протоколе нет возможности добавить атрибуты для контрагента (форму собственности и наименование)

### ISSUE THREAD

**Issue by LitJane** [nemoware/gpn-analyse-ui#115]
6. Протокол РЕА_Шторм_Услуги.docx

![image](https://user-images.githubusercontent.com/55797683/75552215-dec6c300-5a46-11ea-9f88-c17bd46c696a.png)

**Comment by IvanKrivosh** [comment]
![image](https://user-images.githubusercontent.com/52923077/75658826-02258400-5c7a-11ea-94d5-d2814ac727a0.png)
