### ISSUE TITLE
"Все ДО" бесследно исчезли

### ISSUE THREAD

**Issue by SergeyShalaevsky** [nemoware/gpn-analyse-ui#123]
при создании аудита, в дропе "Выбрать ДО" пропал пункт "Все ДО"

**Comment by eliseysinkevich** [comment]
так я же убрал json с субсидарями, и они тянутся из базы. причем коллекция на вашей стороне заполняется

**Comment by compartia** [comment]
@SergeyShalaevsky will only work with analyser v1.7.3 https://github.com/nemoware/analyser/releases/tag/v1.7.3
