### ISSUE TITLE
Редактирование атрибута "Псевдоним контрагента"

### ISSUE THREAD

**Issue by Selgis** [nemoware/gpn-analyse-ui#124]
Во время автоматического анализа протоколов система находит атрибут "Псевдоним контрагента", но нельзя выбрать данный атрибут во время ручной разметки протоколов для корректировки не верно размеченных системой атрибутов.
![image](https://user-images.githubusercontent.com/62250804/78895622-d2874a00-7a77-11ea-9936-692a1f4b5b90.png)
P.S. Атрибуты автоматического режима должны быть приравнены к атрибутам ручной разметки

**Comment by IvanKrivosh** [comment]
@eliseysinkevich проверить нужно состав атрибутов для типов документа.

**Comment by IvanKrivosh** [comment]
![image](https://user-images.githubusercontent.com/52923077/79115961-e5f42700-7d8f-11ea-959b-5a6a4d3a1394.png)
