### ISSUE TITLE
confidence юзерских атрибутов должен быть разумным

### ISSUE THREAD

**Issue by compartia** [nemoware/gpn-analyse-ui#126]
разумным == 1,  0 или null

<img width="742" alt="Capture d’écran 2020-05-14 à 11 46 52" src="https://user-images.githubusercontent.com/7677437/81890557-cfccc700-95d8-11ea-9dad-6504bf30fbfc.png">

**Comment by vanyasav** [comment]
Confidence для всех user attributes теперь 1.
bb2ddf878d48743475d0da1dfcfbe1afd7f8dc04
