### ISSUE TITLE
Не отображается дата и время изменения документа

### ISSUE THREAD

**Issue by Selgis** [nemoware/gpn-analyse-ui#129]
При ручной разметке документа во вкладке "Анализ" не отображается дата и время изменения документа.
![12345](https://user-images.githubusercontent.com/62250804/82824047-46a77100-9eb1-11ea-9feb-b40e4f9e82db.jpg)

**Comment by IvanKrivosh** [comment]
@Selgis а где должна отображаться дата изменения?

**Comment by IvanKrivosh** [comment]
@SergeyShalaevsky можешь приложить json документа, который без даты обработки?

**Comment by SergeyShalaevsky** [comment]
[doc.txt](https://github.com/nemoware/gpn-analyse-ui/files/4681528/doc.txt)
документ приаттачен

**Comment by IvanKrivosh** [comment]
@Selgis готово: 

![image](https://user-images.githubusercontent.com/52923077/82893052-24692e00-9f59-11ea-8311-b041da243990.png)

Во всех ли статусах мы должны показывать данную дату, т.к. после манипуляций юзера с атрибутами дата предыдущей обработки может быть не актуальной для него, например, статус "Загружен, ожидает анализа".

![image](https://user-images.githubusercontent.com/52923077/82893223-5a0e1700-9f59-11ea-8fda-ad431d1504e5.png)

**Comment by LitJane** [comment]
@IvanKrivosh  предлагаю отображать дату для статуса "Анализ завершен".
