### ISSUE TITLE
Разметка атрибута "Сумма" в протоколах с несколькими повестками дня и разными контрагентами

### ISSUE THREAD

**Issue by Selgis** [nemoware/gpn-analyse-ui#138]
Встречаются протоколы, в которых внутри одной повестки дня дочернее общество выделяет разные суммы разным контрагентам, в таких протоколах можно выделить только одну сумму с полными атрибутами (сумма, валюта, знак):
http://gpn-audit.nemosoft.ru/#/audit/edit/5eea0d32d658f903ad1d979b
Также, встречаются протоколы, в которых разными пунктами повестки дня выделяются суммы разным контрагентам, либо увеличиваются доли в уставных капиталах, в таких протоколах тоже невозможно корректно разметить  атрибуты суммы:
http://gpn-audit.nemosoft.ru/#/audit/edit/5eea0d33d658f903ad1d97c4
Для быстрого и корректного завершения ручной разметки протоколов, необходимо добавить возможность выделения внутри протокола атрибутов суммы как внутри одного пункта повестки дня, так и в нескольких

**Comment by IvanKrivosh** [comment]
@Selgis можешь приложить json?

**Comment by IvanKrivosh** [comment]
Ошибка выявлена на любом дочернем атрибуте: если в одной повестки дня 2 атрибута 'Наименование контрагента', то 2й атрибут при сохранении перетирает 1й. Нужно проверять на наличие такого атрибута в списке, и при необходимости добавлять порядковый номер, по аналогии с суммами в уставе: AllMembers/Lawsuit/constraint-min-6
