### ISSUE TITLE
Повторное использование ранее загруженных уставов

### ISSUE THREAD

**Issue by SergeyShalaevsky** [nemoware/gpn-analyse-ui#140]
Надо добавить в диалог создания аудита список подходящих (по ДО и датам) уставов, которые уже загружены в систему. Причем в этом списке следует показывать даты действия уставов, т.е. дата начала действия - это дата в самом уставе, а дата окончания - это дата следующего в хронологическом порядке устава для выбранного ДО.
Также в аудит надо добавить коллекцию ссылок на эти уставы, а из самих уставов убрать ссылку на аудит.

**Comment by compartia** [comment]
@SergeyShalaevsky а некстати, в последней версии я кэширую эмбеддинги на диск, что заметно ускоряет повторный анализ даже уставов

**Comment by SergeyShalaevsky** [comment]
тут дело не только в ускорении, но и в избавлении от повторной доразметки устава, т.к. он может быть актуален для нескольких аудитов
+ об этом уже договорились с гпн

**Comment by IvanKrivosh** [comment]
@SergeyShalaevsky, если для нескольких аудитов в список документов для анализа был включен один и тот же устав, должна ли быть проверка на дублирование этого устава (скажем проверка по дате, чтобы исключить данный файл из анализа и использовать уже ранее проанализированный файл)? Если анализируем все документы, которые включены в аудит, то при наличии 1 устава в разных аудитах, по какому принципу происходит ручной выбор этого устава (в разных версиях устава может отличаться атрибутивная составляющая)?

**Comment by SergeyShalaevsky** [comment]
основная идея - это переиспользование одного и того же устава в разных аудитах Сами уставы могут не меняться годами, но каждый аудит в текущей системе может потребовать ручной доразметки одного и того же устава в разных аудитах одного ДО. 
Вообще тебе надо просто показать список подходящих уставов, но сравнить ты их по датам с уставами из аудита не сможешь, т.к. определение даты дока переехало в анализатор.
Предлагаю просто сформировать коллекцию из подходящих уставов в системе + уставы из аудита, а дальше анализатор после фазы нахождения аттрибутов уже сам решит, какие будут использованы и удалит лишние.

**Comment by eliseysinkevich** [comment]
* Запрос, который делал @vanyasav в ветке `issue_144`, очень похож по сути на тот, который был нужен нам, поэтому мы отбранчевались от его ветки, слегка подправили тот запрос и воспользовались им. Надо бы в будущем их объединить..  
* Добавили в сущность документа признак `isActive`. При создании аудита будут отображаться уставы, у которых вообще нет этого признака, либо у него значение true.  
* Если при создании аудита будут добавлены уставы, они попадут в аудит в массив `charters`.  
* В список документов аудита (при отображении) эти уставы тоже попадут  

![image](https://user-images.githubusercontent.com/17770586/88642488-3b4b0e80-d0c9-11ea-90a4-b324b10d927e.png)

**Comment by SergeyShalaevsky** [comment]
при выборе * Все ДО - ошибка

**Comment by SergeyShalaevsky** [comment]
надо убрать надмозговые однодневные уставы

**Comment by IvanKrivosh** [comment]
> при выборе * Все ДО - ошибка

В чем именно ошибка?

![image](https://user-images.githubusercontent.com/52923077/88647555-c8449680-d0ce-11ea-98ab-7541f83bf9d9.png)

**Comment by SergeyShalaevsky** [comment]
у меня в консоли вот так
![image](https://user-images.githubusercontent.com/51235093/88647845-1a85b780-d0cf-11ea-8f94-51943d4d211b.png)

**Comment by IvanKrivosh** [comment]
Если в выборку по ДО попали  уставы без даты в атрибутах, как обрабатывать какой устав? Просто показать, что мол дата не определена?

**Comment by IvanKrivosh** [comment]
Хотя наверное вообще не корректно предлагать такой устав для выбора, т.к. он не есть верно размечен.

**Comment by SergeyShalaevsky** [comment]
> Если в выборку по ДО попали уставы без даты в атрибутах, как обрабатывать какой устав? Просто показать, что мол дата не определена?

его либо не показывать здесь, либо показывать, но без права выбора

**Comment by SergeyShalaevsky** [comment]
еще заметил, что в массив уставов в аудите не попадает устав, который взят из файловой системы, его бы тоже надо туда включить и еще у таких уставов надо убрать auditId, чтобы он не был удален с аудитом, либо при удалении аудита не удалять уставы.

**Comment by eliseysinkevich** [comment]
сделал
