### ISSUE TITLE
Таб "Анализ": Не показывается сумма, которая была введена юзером

### ISSUE THREAD

**Issue by compartia** [nemoware/gpn-analyse-ui#142]
steps to reproduce:
1) открыть договор на редактирование
2) удалить сумму
3) пометить сумму вручную, сохранить,

<img width="169" alt="Capture d’écran 2020-07-13 à 09 20 31" src="https://user-images.githubusercontent.com/7677437/87261862-70146e80-c4ea-11ea-8d12-abc82c19c73b.png">

**Comment by IvanKrivosh** [comment]
@vanyasav @compartia я категорически извиняюсь, что влезаю не в свою issue:

Для вывода суммы договора и валюты в журнале используются следующие атрибуты sign**_**value**_**currency/value и sign**_**value**_**currency/currency, но после сохранения они имеют вид: sign**-**value**-**currency/value и sign**-**value**-**currency/currency. Поддерживается оба написания атрибутов?

**Comment by IvanKrivosh** [comment]
В файле для перевода есть записи по обоим вариантам написания:

![image](https://user-images.githubusercontent.com/52923077/87288483-1456df00-c504-11ea-8ec2-2424df4a9bcf.png)

**Comment by compartia** [comment]
> я категорически извиняюсь, что влезаю не в свою issue:

я не менее категориально приветсв ую, вот скрины распоследней базы
(в целом, некий бардак с делимитерами, но подчеркивания победили тут)

<img width="351" alt="Capture d’écran 2020-07-13 à 17 25 52" src="https://user-images.githubusercontent.com/7677437/87288813-6876b900-c52e-11ea-9a2f-30e33d08faf7.png">

<img width="267" alt="Capture d’écran 2020-07-13 à 17 26 39" src="https://user-images.githubusercontent.com/7677437/87288796-63b20500-c52e-11ea-8b27-180fb435f497.png">

**Comment by IvanKrivosh** [comment]
Переименованы атрибуты, убран везде replace c '_' на '-'.

**Comment by vanyasav** [comment]
На скрине два одинаковых договора, второй после разметки суммы пользователем, но сумма договора записана в разные ключи.
![image](https://user-images.githubusercontent.com/37312123/87918853-a40a0980-ca7f-11ea-8002-ded46cad844f.png)

**Comment by IvanKrivosh** [comment]
Атрибут "Сумма договора" - текстовое поле. Данный атрибут содержит 3 дочерних: знак, сумма и валюта.
Вариант, который представлен на скриншоте (https://github.com/nemoware/gpn-analyse-ui/issues/142#issuecomment-660897455) - не доразмеченный документ.
Корректная разметка выглядит следующим образом:
![image](https://user-images.githubusercontent.com/52923077/88566002-0e9de500-d03e-11ea-9ffe-73ead6bbc014.png)
Некорректная разметка:
![image](https://user-images.githubusercontent.com/52923077/88566368-9257d180-d03e-11ea-9f4d-8859bc5b8a0e.png)

**Comment by vanyasav** [comment]
Теперь пользователь увидит предупреждение при некорректной разметке суммы договора.
![image](https://user-images.githubusercontent.com/37312123/93465032-de165100-f8f2-11ea-94f3-8bc6c06fea12.png)
