### ISSUE TITLE
Разметка в Уставах ограничений с процентами

### ISSUE THREAD

**Issue by LitJane** [nemoware/gpn-analyse-ui#157]
В Уставах требуется размечать ограничение по Крупной сделки с макс./мин. порогом в %.
На данный момент это невозможно, так как требуется обязательное указание Валюты.
![image](https://user-images.githubusercontent.com/55797683/95848543-dbbedf80-0d56-11eb-9167-4198d645a544.png)

**Comment by vanyasav** [comment]
Такая ситуация только в уставах возможна или для всех ограничений проверку на указание валюты убрать?

**Comment by SergeyShalaevsky** [comment]
тут валюта будет %, думаю на ui стоит изменить название валюта, на единица измерения(ед. изм.)
