### ISSUE TITLE
Добавить окно выбора файла

### ISSUE THREAD

**Issue by LitJane** [nemoware/gpn-analyse-ui#166]
При запуске аудита добавить окно выбора файла, вместо копипаста ссылки.
И при добавлении Устава тоже.
По возможности срочно :)))

**Comment by compartia** [comment]
Тут нужно учитывать, что юзеры и сервер "находятся" на разных "компьютерах". Путь к файлам должен быть доступен серверу, но не обязательно юзеру.

**Comment by thingumajig** [comment]
ГПН выносит мозХ, они не могут, как любые пользователи, правильно ввести .... ничего они не могут ввести правильно с первого раза.
Поэтому предлагаю madhyamā pratipad: 
Никаких окон! Но у них зафиксирована папка/шара куда они херачат свои файлы. 
Дайте возможность вводить только имя той папки, которую они создали внутри фиксированной шары.
И правильно сообщайте ошибку если конкатенированный путь неправильный, а то сейчас какое-то невнятное сообщение

**Comment by thingumajig** [comment]
А по сути, не сделана правильная обработка ошибок ввода! За это нас и пинают

**Comment by vanyasav** [comment]
Это имеется ввиду?
![image](https://user-images.githubusercontent.com/37312123/97019129-9b324380-1558-11eb-8d54-0405fd4b1799.png)

**Comment by compartia** [comment]
@thingumajig эсли это баг, то давай steps to reproduce и expected behaviour.
Иначе -- это feature request

**Comment by compartia** [comment]
+ еще фичареквест:
- [ ] тримать пробелы в начале/конце пути, который ввел юзерица

**Comment by compartia** [comment]
> Но у них зафиксирована папка/шара куда они херачат свои файлы.
> Дайте возможность вводить только имя той папки

Вадик, если папка "зафиксирована".. то зачем ее .. эээ  вводить (она ж зафиксирована)? Поясни плиз

**Comment by thingumajig** [comment]
@compartia Меня тут заставляют объяснение написать и зафиксировать решение. Я пишу пока следующее(добавляйте, коментируйте):

1. Выбирать совсем любые папки на сервере нельзя давать, по соображениями безопасности и философии построения клиент-серверных систем
2. Нынешнее решение - изначально паллиативное, принятое в ожидании роботов
3. Организация загрузки файлов с клиентского компьютера аккуратным образом технически возможно, но требует определённого времени и формулирования требований(ограничения по размеру, обработка ошибки, пересылка большого пакета файлов посредством браузера)

Поэтому, предлагается промежуточное решение, чтобы минимизировать ошибки ввода пользователей:
Общая папка, где создаётся папка для обмена и куда выкладываются файлы известна и постоянна. 
Основная причина неясностей и ошибок в следующем: Адрес её для пользователей и для (linux)сервера по разному выглядит.
Предлагается  в поле указывать только имя временной папки, которая размещена в общей папке и куда выложены файлы для аудита.
Аудитор при старте аудита вписывает в диалоговом окне только имя папки созданной в общей шаре.
Одновременных ~Обезьянок~Аудиторов, заносящих свои файлы, может быть несколько.

**Comment by thingumajig** [comment]
> > Но у них зафиксирована папка/шара куда они херачат свои файлы.
> > Дайте возможность вводить только имя той папки
> 
> Вадик, если папка "зафиксирована".. то зачем ее .. эээ вводить (она ж зафиксирована)? Поясни плиз

Это общая папка-файловая помойка, туда кто угодно может что-то записать и она автоматически зачищается через 3 дня.
Поэтому предпочтительно обосабливаться в своей папочке

**Comment by compartia** [comment]
> 1. Общая папка, где создаётся папка для обмена и куда выкладываются файлы известна и постоянна.

Мне нравится. И давайте решим, что она в конфиге сервера (env) прописана (админом навсегда) 



> 4\. Аудитор при старте аудита вписывает в диалоговом окне только имя своей папки, созданной им в общей шаре.

но на UI ему желательно показать реальный полный абсолютный путь (~~ведущий к прекращению страдания и освобождению от сансары~~)

**Comment by thingumajig** [comment]
> но на UI ему желательно показать реальный полный абсолютный путь (~ведущий к прекращению страдания и освобождению от сансары~)
Да!

**Comment by thingumajig** [comment]
ну например. 

> Это имеется ввиду?
> ![image](https://user-images.githubusercontent.com/37312123/97019129-9b324380-1558-11eb-8d54-0405fd4b1799.png)

@vanyasav  ну в том числе.  надо (про|пере)смотреть этот код свзяанный с открытием папки на предмет того, какие ошибки может совершить юзер при вводе информации и сообщить ему об этом более выпукло.
например
- [ ] во введённой строке есть символы, которые не принадлежат набору символов path в linux, сообщение об этом
- [ ] ошибка: такого пути не существует 
- [ ] может что-то ещё


И да, надо сделать
- [ ] обрезание краевых пробелов
