### ISSUE TITLE
Cannot use the app (branch audit_parser)

### ISSUE THREAD

**Issue by compartia** [nemoware/gpn-analyse-ui#17]
See screensots for details:
( pl #16 )
1
<img width="1251" alt="Capture d’écran 2019-10-16 à 01 51 25" src="https://user-images.githubusercontent.com/7677437/66856326-8e7b2700-efb7-11e9-8c60-18993b3a4665.png">

2
<img width="603" alt="Capture d’écran 2019-10-16 à 01 49 36" src="https://user-images.githubusercontent.com/7677437/66856328-8e7b2700-efb7-11e9-9622-58426facb5b3.png">

3
<img width="728" alt="Capture d’écran 2019-10-16 à 01 45 50" src="https://user-images.githubusercontent.com/7677437/66856330-8e7b2700-efb7-11e9-882e-55208fa0a9cf.png">

4
<img width="480" alt="Capture d’écran 2019-10-16 à 01 44 17" src="https://user-images.githubusercontent.com/7677437/66856331-8f13bd80-efb7-11e9-9f01-797a09e10ec8.png">

**Comment by eliseysinkevich** [comment]
С точки зрения сервера:
В качестве юзера в параметрах запуска передан user1, которого нет в базе. По сути, имитируется ситуация, когда юзер есть в указанной группе AD, но админ не добавил его в список пользователей приложения. Поэтому ему ничего не доступно.

**Comment by eliseysinkevich** [comment]
Запускать из под admin, user2, user3, при этом убедившись, что соответствующий юзер есть в базе и ему даны права (доступно от админа)
