### ISSUE TITLE
Повторы одинаковых недостатков, рекомендаций и рисков в заключении по аудиту

### ISSUE THREAD

**Issue by BondarevaEkaterina** [nemoware/gpn-analyse-ui#185]
![image](https://user-images.githubusercontent.com/72862437/99970439-e2586200-2dac-11eb-89bf-1a04e573d6d9.png)

**Comment by vanyasav** [comment]
Ссылку на аудит, пожалуйста

**Comment by BondarevaEkaterina** [comment]
См. Арктика Медиа

пн, 23 нояб. 2020 г., 22:59 vanyasav <notifications@github.com>:

**Comment by BondarevaEkaterina** [comment]
Сегодня в отчете по ГПН-Заполярье:
![image](https://user-images.githubusercontent.com/72862437/100352747-89800800-2ffe-11eb-96d8-4862f3405d3a.png)

**Comment by vanyasav** [comment]
На данный моменте в самой матрице рисков повторяются рекомендации и недостатки для различных сценариев

**Comment by BondarevaEkaterina** [comment]
В том то и дело, что нарушения могут быть одинаковые в одном аудите, а рекомендация должна быть одна для всех однотипных нарушений.
