### ISSUE TITLE
При изменении устава должны заново анализироваться договоры

### ISSUE THREAD

**Issue by BondarevaEkaterina** [nemoware/gpn-analyse-ui#186]
Ссылку на аудит см. в Телеграм

**Comment by LitJane** [comment]
Дополнение: 
При внесении изменений в Устав должны запускаться заново на анализ договоры тех Проверок, для которых этот устав был указан при запуске проверки или использовался по умолчанию (из папки). 
При этом договоры проверок статус, которых "Подтвержден", остаются неизменными и  не должны отправляться на повторный анализ.
