### ISSUE TITLE
Неправильная разметка в протоколе

### ISSUE THREAD

**Issue by BondarevaEkaterina** [nemoware/gpn-analyse-ui#188]
Ссылка на протокол: http://gpn-audit.nemosoft.ru/#/audit/edit/5fbf75ad5d05d73d0295fa71
![image](https://user-images.githubusercontent.com/72862437/100426352-c51fde00-30a1-11eb-9f20-9f6ac8a1d1ab.png)

**Comment by vanyasav** [comment]
nemoware/analyser#242

**Comment by compartia** [comment]
depends on https://github.com/nemoware/analyser/issues/242

**Comment by BondarevaEkaterina** [comment]
Еще пример:
![image](https://user-images.githubusercontent.com/72862437/101321994-526beb00-3877-11eb-843b-6baa2ca671c8.png)
В протоколе:
![image](https://user-images.githubusercontent.com/72862437/101322054-69aad880-3877-11eb-89b4-7969bd077920.png)

**Comment by compartia** [comment]
Такое исправится, когда мы сделаем https://github.com/nemoware/analyser/issues/242
