### ISSUE TITLE
Пропала колонка с ДО в аудите НТЦ

### ISSUE THREAD

**Issue by BondarevaEkaterina** [nemoware/gpn-analyse-ui#189]
![image](https://user-images.githubusercontent.com/72862437/100711636-9fa51400-33c2-11eb-9d13-fd8450a11ea8.png)

**Comment by BondarevaEkaterina** [comment]
Задача требует обсуждения - во сколько удобно завтра созвониться?

**Comment by vanyasav** [comment]
На данный момент по логике UI колонка не отображается, если у всех договоров одинаковое наименование ДО
