### ISSUE TITLE
фильтровать файлы во входной директории

### ISSUE THREAD

**Issue by SergeyShalaevsky** [nemoware/gpn-analyse-ui#20]
Sergey Shalaevsky, [22.10.19 15:45]
еще неплохо бы фильтровать файлы по расширению: doc, docx во входной директории

Sergey Shalaevsky, [22.10.19 15:45]
а то сейчас указал папку где кроме доков лежали еще левые файлы, все завалилось

Sergey Shalaevsky, [22.10.19 15:48]
кстати даже если парсер вернул ошибку, то надо слать дальше доки, а ошибку пока логировать, в будущем видимо будет спец коллекция ошибок в аудите

**Comment by compartia** [comment]
в дальнейшем будут еще и pdf ->
сервер не должнен особо понимать, что умеет парсить парсер.
если парсер не смог, он должен вернуть внятную ошибку.

**Comment by SergeyShalaevsky** [comment]
не согласен, дело не в парсере, а в том что на вход принимает система, pdf вообще не пойдет в парсер напрямую

**Comment by compartia** [comment]
pdf -- просто пример тут.
не хочется размазывать бизнес-логику по приложению.
если в какой-то момент придется выяснять, почему какой-то док не попал в аудит, то должно быть как можно меньше узлов, где он мог пропасть.
поэтому, мне не хочется, чтобы сервер занимался фильтрацией, а тем более -- фильтрацией просто по расширению файла

**Comment by compartia** [comment]
> pdf вообще не пойдет в парсер напрямую

не хотелось бы менять сервер, когда мы вдруг научимся парсить pdf rtf txt

**Comment by SergeyShalaevsky** [comment]
раз уж решили использовать его, как дирижера, то ему придется немного понимать и бизнес-логику, на примере все того же пдф, его надо будет отправить в другой сервис, а из отфильтрованных файлов надо формировать список, которые мы не поддерживаем

**Comment by SergeyShalaevsky** [comment]
> не хотелось бы менять сервер, когда мы вдруг научимся парсить pdf rtf txt

поддерживаемые формат должны быть в конфиге

**Comment by compartia** [comment]
> поддерживаемые формат должны быть в конфиге

 - нет. Если я в конфиг добавлю jpg, то это не станет означать, что парсер сумеет их обрабатывать. И если я удалю оттуда docx, то ... что?

> раз уж решили использовать его, как дирижера

 - не решили. Это заблуждение. 

 > его надо будет отправить в другой сервис

- нет, с точки зрения сервера -- он неглядя отправляет его _куда-то_ на обработку. А _там_ уже решается, кем чем его парсить и вообще умеем ли.

В любом случае, если тебе на вход придет док, который по какой-то причине не может быть обработан, ты не должен падать (духом) и отвечать "ой умираю", а ответить ошибкой "неможно парсить, потому что .. <dddd>."

**Comment by SergeyShalaevsky** [comment]
> * нет. Если я в конфиг добавлю jpg, то это не станет означать, что парсер сумеет их обрабатывать. И если я удалю оттуда docx, то ... что?
а если наоборот на вход придет jpg, то что его отправим на обработку, в безумной надежде, что вдруг прокатит? :)
конфиг должен быть корректен и не должно быть историй типа, что если я удалю полконфига



> * не решили. Это заблуждение.

я специально спрашивал, кто все это будет дирежировать, и ты мне сам сказал, что это будет сервер (хотя я предлагал отдельный процесс)


> В любом случае, если тебе на вход придет док, который по какой-то причине не может быть обработан, ты не должен падать (духом) и отвечать "ой умираю", а ответить ошибкой "неможно парсить, потому что .. ."

так сейчас сервак вываливается, когда я ему присылаю ошибку :)

**Comment by compartia** [comment]
> я специально спрашивал, кто все это будет дирежировать, и ты мне сам сказал, что это будет сервер (хотя я предлагал отдельный процесс)

если я и правда так сказал, то я был тогда моложе, глупее и при этом усталый.

> так сейчас сервак вываливается, когда я ему присылаю ошибку :)

сервак тут неправ. Ему следует переосмыслить свое поведение.

**Comment by SergeyShalaevsky** [comment]
так в итоге не понятно, кто же все будет дирижировать?

я так и не услышал, какого-то хорошего аргумента, что бы не отсеивать сразу явно не поддерживаемые форматы(с показом этих файлов юзеру, что вот их мы не поддерживаем)

**Comment by compartia** [comment]
> так в итоге не понятно, кто же все будет дирижировать?

Предыстория. Мы где-то называли это "фаза 0"

 1. В некой фтп папке в результате недетерминистического стохастического и местами мистического процесса спорадически самозарождаются файлы.
 2. Юзер (тайными каналами) узнает адрес этой папки, и через UI дает ее адрес серверу.
 3. Сервер умеет читать фтп, и он это делает - оптимистично читает все файлы и отдает их малознакомому парсеру.
 3. Парсер отвечает серверу json-ами, сервер складывает ответы в базу.
 4. Юзер видит, какие файлы пойдут на аудит, а какие -- нечитабельны.

 в этой схеме какой-то "дирижер" мне не виден. 

> я так и не услышал, какого-то хорошего аргумента, что бы не отсеивать сразу явно не поддерживаемые форматы(с показом этих файлов юзеру, что вот их мы не поддерживаем)

В этой схеме есть только 1 точка принятия решению по файлу -- парсер.

**Comment by SergeyShalaevsky** [comment]
хорошо, пусть будет парсер. Надеюсь через месяц не услышу очередную историю про молодого Артема :)

Вобщем из всего остается только пофиксить, чтобы сервак не заваливался, если получает ошибку

**Comment by compartia** [comment]
посчитаем фильтры:
во-перывых, как-то уже на фтп попадают именно нужные файлы, можно уверовать, что там тоже какая-то фильтрация.
во-вторых, сам парсер все равно должен уметь сражаться с нечестью
в-третьих, анализатор тоже может что-то не хотеть анализировать потом
--> то есть, сервер уже может расслабиться и не фильтровать.

А про Артема.. есть шанс, что он начнет молодеть.

**Comment by eliseysinkevich** [comment]
сервер понял свою ошибку и исправил свое поведение. он больше так не будет...
фильтрацию пока не делаем, просто логаем ошибку

**Comment by compartia** [comment]
@eliseysinkevich  

> просто логаем ошибку

А можешь сюда вкопипастить пример "логания" ошибки?

**Comment by eliseysinkevich** [comment]
StatusCodeError: 400 - "{\"timestamp\":\"2019-10-22T15:00:38.817+0000\",\"status\":400,\"error\":\"Bad Request\",\"message\":\"JSON parse error: Cannot deserialize value of type `com.nemo.document.parser.DocumentFileType` from String \\\"JPG\\\": value not one of declared Enum instance names: [DOCX, DOC]; nested exception is com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `com.nemo.document.parser.DocumentFileType` from String \\\"JPG\\\": value not one of declared Enum instance names: [DOCX, DOC]\\n at [Source: (PushbackInputStream); line: 1, column: 470044] (through reference chain: com.nemo.document.parser.web.DocumentParserRequest[\\\"documentFileType\\\"])\",\"path\":\"/document-parser\"}"

**Comment by compartia** [comment]
@eliseysinkevich 
а что в базу пишется для дока, который не смог-ся?

**Comment by eliseysinkevich** [comment]
а он пока в базу не идет.. а должен?

**Comment by compartia** [comment]
@eliseysinkevich  за других юзеров не скажу, но я бы хотел видеть на юае, что некоторые доки не прошли парсинг

**Comment by eliseysinkevich** [comment]
Мы так понимаем, что есть два типа файлов, которые могут не пройти парсинг
- файлы, которые в принципе и не должны туда попасть (всякие jpg и png)
- и файлы, с которыми парсер не справился
Так вот для обоих ли вариантов нужно что-то выводить на ui?

**Comment by compartia** [comment]
> для обоих ли вариантов нужно что-то выводить на ui?

тут выше из переписки вытекает, что сервер не обязан знать о типах файлов.
-> И если все согласны, то этот вопрос можно снять

**Comment by eliseysinkevich** [comment]
это понятно
но
для этих файлов парсер вернет разные ошибки, и в зависимости от этого я могу менять поведение сервера. нужно ли пользователю знать, что у него на ftp завалялся какой-то hello.jpg?

**Comment by compartia** [comment]
если исходить из предположения, что файлы нам будут давать в папке осознанно, то всех их нужно парсить. Я представляю себе, что если парсер не смог (не захотел, не успел) что-то прочитать, то он возвращает более-менее развернутое сообщение об ошибке. 
Сообщение пишем в базу и показываем на Юае.
В рамках MVP можно не мудрить с типами ошибок -- неподдержиывемый формат там или внутренние проблемы -- не так и важно, главное, чтобы кто-то заметил, что есть ошибка и напряг девелоперов.

**Comment by compartia** [comment]
> и в зависимости от этого я могу менять поведение сервера

поведение сервера от типа ошибок не должно зависеть. На мой взгляд, сервер вообще мог бы и не знать, что там ошибка -- если он пишет в базу точно то, что вернул парсер.

Другое дело, потом, после мвп, когда соберем фидбек от юзера, может быть, за доп. деньги разные ошибки будем красить на юае разными цветами

**Comment by compartia** [comment]
@SergeyShalaevsky @eliseysinkevich 

> `StatusCodeError: 400 - "{"timestamp":"2019-1 ... `

а в ошибковом ответе парсера можно тоже иметь поле "версия", как и при нормальном ответе?

**Comment by eliseysinkevich** [comment]
> сервер вообще мог бы и не знать, что там ошибка

кстати, не мог бы. потому что, если код ответа >=400, то request.post() выкидывает exception

**Comment by SergeyShalaevsky** [comment]
> поведение сервера от типа ошибок не должно зависеть. На мой взгляд, сервер вообще мог бы и не знать, что там ошибка -- если он пишет в базу точно то, что вернул парсер.
> 
> Другое дело, потом, после мвп, когда соберем фидбек от юзера, может быть, за доп. деньги разные ошибки будем красить на юае разными цветами

я бы на данном этапе только отличал код 200(все ок) и не 200(какая-то ошибка), различать ошибки не стоит, просто писать все в базу. Но опять же зависит от того, будет ли у нас некая коллекция проблем/ошибок в базе или нет.

**Comment by SergeyShalaevsky** [comment]
> а в ошибковом ответе парсера можно тоже иметь поле "версия", как и при нормальном ответе?

даже нужно, включу это в следующую версию.

**Comment by compartia** [comment]
so,
кто осмелится закрыть?
