### ISSUE TITLE
Вопросики

### ISSUE THREAD

**Issue by vanyasav** [nemoware/gpn-analyse-ui#206]
Сколько сумм договора может быть в предмете?
Сколько их может быть в целом в документе? 

Сколько раз может быть размечен один вид органа управления в уставе?

Сколько раз может быть размечен один вид сделки в органе управления?

Сколько раз можно выделять в пункте повестки дня атрибуты? Сейчас ограничения нет (можно n раз разметить наименование ДО, например).

**Comment by BondarevaEkaterina** [comment]
Сколько сумм договора может быть в предмете?
Сколько их может быть в целом в документе?
- Множество, зависит от типа договоров. См.:
[Описание интерфейса для определения цены в договорах.docx](https://github.com/nemoware/gpn-analyse-ui/files/5701050/default.docx)
- Наиболее частый вариант, если сумма договора указана в предмете: цена без НДС, сумма НДС, сумма с НДС.

Сколько раз может быть размечен один вид органа управления в уставе?
- Один.

Сколько раз может быть размечен один вид сделки в органе управления?
- Множество раз (например, "Уставной капитал").

Сколько раз можно выделять в пункте повестки дня атрибуты? Сейчас ограничения нет (можно n раз разметить наименование ДО, например).
- Множество раз (например, в протоколах одним пунктом может быть одобрено множество сделок).

**Comment by compartia** [comment]
Ответики


On Wed, 16 Dec 2020 at 13:06, vanyasav <notifications@github.com> wrote:

> Сколько сумм договора может быть в предмете?
>

В нормальном документе, конечно, от нуля до одной. Вообще местоположение
суммы не связано с предметом. Да, они могут пересекаться.

В ненормальном документе сумм может быть сколь угодно много, но мы из не
умеем складывать

>
> Сколько их может быть в целом в документе?
>
Выше написал

> Сколько раз может быть размечен один вид органа управления в уставе?
>

Один. Мне пока не попадались экзотические уставы. Обычно там для каждого
органа один большой раздел

> Сколько раз может быть размечен один вид сделки в органе управления?
>
произвольно

> Сколько раз можно выделять в пункте повестки дня атрибуты? Сейчас
> ограничения нет (можно n раз разметить наименование ДО, например).
>
Произвольно, но... это скорее нужно для обучения сетки, а не для анализа
нарушений — для анализа всего по одному и вообще, если атрибутов больше, то
алгоритм должен бы усомниться в себе.

Пункт повестки вообще может содержать что угодно, не обязательно связанное
с договором.
