### ISSUE TITLE
Доработка Заключения

### ISSUE THREAD

**Issue by LitJane** [nemoware/gpn-analyse-ui#211]
- [ ] 1. Форматирование шаблона

- [ ] 2.  В титульном листе выводить краткое наименование ДО (когда будет заведено) ;

- [x] 3. Добавить/изменить формулировку в вводной части:

```
2. Документальную проверку ООО «Арктика Медиа» в том числе:
2.1. выборочную  проверку представленной документации на предмет полноты, достоверности, правильности оформления (соответствие объема представленной документации электронной базе ДКПС).
2.2. выборочную проверку договорных документов Общества на предмет наличия/отсутствия корпоративных одобрений и их достоверности.
2.3.	проверку соблюдения Обществом требований действующего законодательства РФ по размещению информации на федеральных ресурсах.
2.4. 	проверку соблюдения Обществом требований действующего законодательства РФ по включению в ЕГРЮЛ актуальной/достоверной информации.
```

- [x] 4. Добавить в Сильные стороны (в начало):

•	Утверждено Положение о распределении прибыли Общества.
•	Утверждено Положение о Генеральном директоре Общества.
•	Утверждено Положение о Совете директоров Общества (в период действия СД).

- [ ] 5. Если один из разделов пуст - запросить типовые формулировки заполнения разделов.

**Comment by LitJane** [comment]
6. Добавить 2 раздела (в оглавление, в ui, в шаблон):
**Результаты проверки соблюдения _<<ДО>>_ положений действующего законодательства РФ о размещении юридически значимых сведений о фактах деятельности Общества** 
В рамках проведения проверки соблюдения Обществом требований по размещению на федеральном информационном ресурсе – в Едином федеральном реестре (ЕФРСФДЮЛ) юридически значимых сведений о фактах деятельности Общества нарушения не выявлены – вся содержащаяся в ЕФРСФДЮЛ информация об Обществе является актуальной и достоверной. 

**Результаты проверки соблюдения _<<ДО>>_  положений действующего законодательства РФ по включению в ЕГРЮЛ актуальной/достоверной информации**
В рамках проведения проверки соблюдения Обществом положений действующего законодательства РФ по включению в ЕГРЮЛ актуальной/достоверной информации нарушения не выявлены – вся содержащаяся в ЕГРЮЛ информация об Обществе является актуальной и достоверной.

**Comment by vanyasav** [comment]
А что редактировать, если атрибута нет?
