### ISSUE TITLE
Ошибка с суммой во вкладке Нарушения

### ISSUE THREAD

**Issue by BondarevaEkaterina** [nemoware/gpn-analyse-ui#217]
![Ошибка с суммой 2](https://user-images.githubusercontent.com/72862437/103293543-29b3bd00-4a01-11eb-8770-0eada99dea0c.png)

**Comment by BondarevaEkaterina** [comment]
Последняя проверка ГПН-Снабжение. Сумма была размечена вручную

**Comment by vanyasav** [comment]
Поправил для стоимости договора и повестки дня
Для тех документов, что уже размечены, но ошибка есть, надо будет пересохранить документ
