### ISSUE TITLE
Интерфейс вкладки Анализ при проверке проекта ДД во вкладке Предпроверка

### ISSUE THREAD

**Issue by BondarevaEkaterina** [nemoware/gpn-analyse-ui#237]
Во вкладке «Анализ» должны выводиться распознанные документы: договор, приложение, дополнительное соглашение, справка о цепочке бенефициаров (приложение и дополнительное соглашение с указанием количества в скобках, если несколько).
При открытии строки «Договор» должна выводиться следующая информация: дата, номер, контрагент, инсайд (фрагмент текста с инсайдом – первая строка с пунктом договора), заинтересованность (наименования юр.лиц либо ФИО выявленных заинтересованных лиц, списком), «!» (индикатор наличия ошибок ), статус.
При открытии строк «Приложение» или «Дополнительное соглашение» должна выводиться следующая информация: дата, номер договора, контрагент, инсайд, «!» (индикатор ошибок), статус.
При открытии строки «Справка о цепочке бенефициаров» должны выводится: дата, контрагент, бенефициары (списком, если несколько), «!» (индикатор ошибок), статус.

**Comment by BondarevaEkaterina** [comment]
Предлагаю при открытии строки "Договор" убрать номер договора, но поставить сумму (желательно при крупной сделке)

**Comment by LitJane** [comment]
А я вроде рисовала вкладку анализ, и там номера договора не было вообще....
