### ISSUE TITLE
Новые атрибуты при разметке договора (дополнительного соглашения, приложения)

### ISSUE THREAD

**Issue by BondarevaEkaterina** [nemoware/gpn-analyse-ui#241]
- «Инсайдерская информация»:

    o	может быть размечена в атрибуте «Предмет», далее разметка текста с указанием на ИИ, далее выбор типа инсайдерской информации из списка согласно справочнику;
    o	может быть размечена в другом месте документа, далее выбор типа инсайдерской информации из списка согласно справочнику.

- «Должностное лицо», далее по отдельности разметка фамилии, имени (если имен несколько, то все сразу), отчества (отчество, если есть) либо инициалов (если вместо имени и отчества есть только инициалы, то пользователь размечает «инициалы»).

**Comment by vanyasav** [comment]
> o может быть размечена в атрибуте «Предмет», далее разметка текста с указанием на ИИ, далее выбор типа инсайдерской информации из списка согласно справочнику;

Пусть пользователь решит добавить новый тип инсайда.
А как анализатор будет узнавать о новом типе инсайдерской информации? Может лучше сделать фиксированный список, как с предметами договоров? @compartia
