### ISSUE TITLE
Мелкие огрехи UI (скриншот)

### ISSUE THREAD

**Issue by compartia** [nemoware/gpn-analyse-ui#253]
<img width="1286" alt="Screenshot 2021-05-29 at 10 19 35" src="https://user-images.githubusercontent.com/7677437/120055288-b07bcd00-c067-11eb-8c28-1dd9bb832987.png">

Тестилось в Safari (но в хроме похоже)

**Comment by LitJane** [comment]
В Хроме и в Эдже  такой проблемы нет.
![image](https://user-images.githubusercontent.com/55797683/120182402-05117a80-c217-11eb-9f06-ff1424b8834d.png)
