### ISSUE TITLE
Разметка срока аренды (период/диапазон)

### ISSUE THREAD

**Issue by BondarevaEkaterina** [nemoware/gpn-analyse-ui#255]
Варианты разметки времени аренды:

- Период: число месяцев или дней
- Диапазон: с ... по ... (календарь)

**Comment by SergeyShalaevsky** [comment]
#193

**Comment by BondarevaEkaterina** [comment]
Срок аренды считается по количеству периодов за которые начисляется арендная плата (как правило в пункте "Срок действия договора"). Период (месяц / день) определяется из размера арендной платы (Х...Х руб. в месяц / ХХ руб. в день), соответственно в договорах аренды необходимо размечать "период" рядом с суммой арендной платы (как правило в пункте "Сумма договора"). Далее размечается количество периодов - может быть указано: "договор заключен на 11 месяцев", могут быть указаны даты "с... по..." - в этом случае система должна считать количество периодов по календарю.

**Comment by BondarevaEkaterina** [comment]
Если в уставах указан срок аренды, от которого необходимо одобрение сделки коллегиальным органом, то необходимо его размечать (как правило это 1 год). Соответственно в нарушения должны выводиться договоры, срок которых (по сумме размеченных периодов) превышает срок в уставе.
Пример: 
![image](https://user-images.githubusercontent.com/72862437/126172459-2114c4c9-6432-47dd-8986-c97907cd1dc4.png)

**Comment by compartia** [comment]
schema proposal
@vanyasav 


```java
"terms":{
      "description": "Сроки/периоды договора",
      "allOf": [
        {"$ref": "#/definitions/tag"},
        {
          "properties": {
            "term":{
              "description":"Количество периодов. Пример: сроком на **11** (одиннадцать) месяцев",
              "$ref": "#/definitions/numeric_tag"
            },
            "term_unit":{
              "description":"Продолжительность периода. Пример: месяцев, лет, дней",
              "$ref": "#/definitions/string_tag"
            },
            "date_start": {
              "description":"Дата вступления договора в силу",
              "$ref": "#/definitions/date_tag"
            },
            "date_stop": {
              "description":"Дата окончания сил договора",
              "$ref": "#/definitions/date_tag"
            }
          }
        }
      ]
    },
```

**Comment by compartia** [comment]
и для суммы за период аренды пока предлагается такая структура
(@vanyasav покритикуй, плиз)
 ```java

    "contract": {
      "properties": {

        "price_for_period": {
          "$ref": "#/definitions/currency_value",
          "description":"Не общая сумма договора, а стоимость за период, например, за месяц аренды",
        },
       ...
```
