### ISSUE TITLE
Дополнения после демо

### ISSUE THREAD

**Issue by compartia** [nemoware/gpn-analyse-ui#26]
## Журнал аудитов
 - [x] убрать кнопки из строк таблицы, клик по cтроке таблицы --> переход к деталям аудита. Строки подсвечивать при наведении курсора, чтобы юзер понял, что из можно нажимать
 - [x] Переименовать колонку “Дата создания аудита”. Содержание: <дата + время>. сортировка аудитов по дате изменения аудита, последний сверху (датой изменения считать дату создания или завершения, что позже было, то и дата)

## Журнал документов
- [x] Журнал документов – убрать иконку/кнопку ворнинг “!”
- [x] Везде убрать порядковый номер
- [x] тип UNKNOWN – подсветить, в тултипе или в скобка написать "не поддерживается"

## Уставы
- [x] График по умолчанию развернут
- [x] Клик по графику приводит к скроллингу дока до соотв. атрибута
- [x] Переименовать атрибуты (названия будут даны отдельно, либо PR c json)
- [x] Редактировать атрибуты для устава
- [x] фикс скроллинга (и скрольчихи)

## Разное
- [x] Помечать измененные атрибуты особым стилем
- [x] убрать чекбоксы из диалога выбора протокола, refer #22 
- [ ] сделать тестовый набор доков и сценарий демонстрации
- [x] номера договоров показывать

![Audit](https://user-images.githubusercontent.com/7677437/69640553-81af2000-1099-11ea-88a1-b427e6c8ccc7.png)

![Audit-files](https://user-images.githubusercontent.com/7677437/69640889-203b8100-109a-11ea-9d03-e73e708905c2.png)

![Audit-analyse](https://user-images.githubusercontent.com/7677437/69641911-f08d7880-109b-11ea-8330-72cfca47dcdb.png)

**Comment by compartia** [comment]
## Редактор протоколов:
- [ ] c протоколом не нужно связывать протокол (нужно: приложениия, договоры)
- [ ] кнопка "глаз" не нужна, -- сама строка может быть кликабельна (ссылкой)
(см. скриншот)

<img width="761" alt="Capture d’écran 2019-11-28 à 16 26 54" src="https://user-images.githubusercontent.com/7677437/69789797-33666200-11fc-11ea-89b2-032e3cc26b76.png">

**Comment by thingumajig** [comment]
А вкладку(?) "Заключения" добавим в TODO?

**Comment by compartia** [comment]
<img width="1498" alt="Capture d’écran 2019-12-09 à 04 18 22" src="https://user-images.githubusercontent.com/7677437/70395630-9c8b7800-1a3b-11ea-923a-7170a3a58be8.png">
