### ISSUE TITLE
новый аудит вечно новый

### ISSUE THREAD

**Issue by compartia** [nemoware/gpn-analyse-ui#28]
steps to reproduce:
1) создать (добавить) новый аудит
2) ждать
3) выбрать строку только что созданного аудита путем нажатия на него.
==> происходит ничто (если не догадаться, что нужно рефрешнуть страницу)

expected:
переход на экран деталей аудита (пусть и пустую)
ЛИБО
авто-рефреш

**Comment by SergeyShalaevsky** [comment]
на самом деле я уже давно говорю, что нужен авто-рефреш, это поможет и переходу между оставшимися статусами

**Comment by compartia** [comment]
> на самом деле я уже давно говорю, что нужен авто-рефреш, это поможет и переходу между оставшимися статусами

да

**Comment by vanyasav** [comment]
Есть готовая ветка с авторефрешем, нет готовое сервера с настроенной репликой
