### ISSUE TITLE
Предпроверка ДД - не отображаются результаты найденной заинтересованности

### ISSUE THREAD

**Issue by LitJane** [nemoware/gpn-analyse-ui#281]
Для договора с суммой больше 1 млрд рублей и явным наличием заинтересованных лиц - не отобразилось ни одного нечестного лица.
http://gpn-audit.nemosoft.ru/#/pre-audit/result/60ebf788cddbb3c487368c32

**Comment by vanyasav** [comment]
Проблема решилась?

**Comment by LitJane** [comment]
@vanyasav если вопрос мне , то да )))
