### ISSUE TITLE
Справочник аффилированных лиц - не сбросить отфильтрованные значения

### ISSUE THREAD

**Issue by LitJane** [nemoware/gpn-analyse-ui#291]
Нет возможности сбросить отфильтрованные значения, а так хотелось бы...

**Comment by vanyasav** [comment]
Возможность есть. 
После нажатия кнопки "Очистить" можно нажать кнопку "Применить" или Enter на клавиатуре для обновления таблицы. 
По такой же логике действуют все фильтры в интерфейсе. 

Возможно, стоит обновлять таблицу сразу по нажатию кнопки "Очистить".

**Comment by LitJane** [comment]
Возможно сделаем, но позднее...
