### ISSUE TITLE
Добавление валют

### ISSUE THREAD

**Issue by BondarevaEkaterina** [nemoware/gpn-analyse-ui#303]
Список валют: [currencies.txt](https://github.com/nemoware/gpn-analyse-ui/files/7060515/currencies.txt)

В выпадающем списке при разметке валют на первых строчках должны быть: рубль, доллар, евро (можно оставить знаки валют, как есть сейчас). Остальные валюты писать ниже по алфавиту, например: Бразильский реал, Казахский тенге, Фунт стерлингов и т.п.

**Comment by vanyasav** [comment]
Валюты были добавлены на UI

**Comment by vanyasav** [comment]
@compartia когда валюты ждать в json схеме дерева?

**Comment by compartia** [comment]
> @compartia когда валюты ждать в json схеме дерева?

https://github.com/nemoware/analyser/commit/6c71bd9574960f2668789d60f80f79311e3186c2
