### ISSUE TITLE
сохранение документа затирает 'analysis.analyze_timestamp`

### ISSUE THREAD

**Issue by compartia** [nemoware/gpn-analyse-ui#33]

**Comment by eliseysinkevich** [comment]
Проверил, не затирает

**Comment by compartia** [comment]
<img width="1330" alt="Capture d’écran 2019-12-13 à 22 53 04" src="https://user-images.githubusercontent.com/7677437/70808774-5d727380-1dfb-11ea-9391-8f25f06a4780.png">

<img width="931" alt="Capture d’écran 2019-12-13 à 22 57 08" src="https://user-images.githubusercontent.com/7677437/70809053-facda780-1dfb-11ea-86da-6534803e202d.png">

**Comment by compartia** [comment]
в этом примере первый док был отредактирован, второй -- нет
