### ISSUE TITLE
В модуле "Уставы" в СКК не сохраняются документы.

### ISSUE THREAD

**Issue by ChernovaZarina** [nemoware/gpn-analyse-ui#346]
В модуле "Уставы" в СКК не работает кнопка сохранения документов. 
После разметки устава пыталась сохранить изменения, но при нажатии на кнопку "сохранить" ничего не происходит, она не работает. Соответственно никакие изменения в разметке уставов не сохраняются.
К тому же при открытие любого из уставов выходит ошибка (на скрине), после нажатия на кнопку "ок" устав открывается.
![image](https://user-images.githubusercontent.com/107481792/175297171-0edf3404-ca79-4a06-b4f7-3a56007392c1.png)

**Comment by vanyasav** [comment]
@ChernovaZarina Есть уставы, которые открываются без этого предупреждения?

**Comment by ChernovaZarina** [comment]
Да, есть два устава.
ГПН-Инвест с датой последнего изменения 06.10.2020
ГАЗПРОМНЕФТЬ ЛУБРИКАНТС ИТАЛИЯ СПА с датой последнего изменения 09.10.2020
