### ISSUE TITLE
Создать "Справочник ограничений по ПСС" (Порядку совершения сделок)

### ISSUE THREAD

**Issue by BondarevaEkaterina** [nemoware/gpn-analyse-ui#348]
Три колонки: Ограничение (ввод текста), Предмет договора (выбор из открывающегося списка предметов договоров), Значение (ввод числа и единицы измерения).

**Comment by BondarevaEkaterina** [comment]
@vanyasav, напиши, пожалуйста, не "Новый риск", а "Новое ограничение". И поменяй местами строки Предмет договора и Ограничение.
![image](https://user-images.githubusercontent.com/72862437/186110168-98ff273a-6b89-473d-b88d-08e4e083741b.png)

**Comment by BondarevaEkaterina** [comment]
@vanyasav, а еще сделай, пожалуйста, чтобы Предмет договора можно было вводить буквами, а значение подставлялось, как при выборе атрибута при разметке договора

**Comment by BondarevaEkaterina** [comment]
@vanyasav, и еще - поля "Значение" и "Единица измерения" не должны быть обязательными

**Comment by SergeyShalaevsky** [comment]
> @vanyasav, и еще - поля "Значение" и "Единица измерения" не должны быть обязательными

@BondarevaEkaterina а как тогда они будут искаться в аттрибутах договора без этих значений? одного предмета договора будет достаточно?

**Comment by BondarevaEkaterina** [comment]
@SergeyShalaevsky, в этом случае - ДА
Там одно из ограничений только по предмету договора.

**Comment by BondarevaEkaterina** [comment]
Изменения справочника по согласованию с заказчиком:
- К каждому ограничению добавить выбор множества предметов договоров из списка;
- При создании/редактировании записи добавить еще одно вводимое значение "Относится к..." и выбор - ГПН, ДО, ГПН и ДО.
