### ISSUE TITLE
Предпроверка ДД. Выводить отсутствие результатов проверок

### ISSUE THREAD

**Issue by BondarevaEkaterina** [nemoware/gpn-analyse-ui#359]
В случае, если система не нашла заинтересованность, инсайд и ограничения по ПСС в Результатах проверки выводить:
- Имя файла,
- Сторона 1 / сторона 2
- При проверке на заинтересованность - "Заинтересованность не найдена"
- При проверке на инсайд - "Возможность передачи инсайдерской информации не найдена"
- При проверке на ПСС - "Ограничения по Порядку совершения сделок не найдены"

**Comment by vanyasav** [comment]
@BondarevaEkaterina Анализатор сейчас стороны записывает в бд, если нарушений нет?
