### ISSUE TITLE
Добавить новый статус анализа документа "Не найдена дата и/или сторона(-ы) для анализа документа"

### ISSUE THREAD

**Issue by BondarevaEkaterina** [nemoware/gpn-analyse-ui#405]
![image](https://user-images.githubusercontent.com/72862437/230588149-7a3ddd5f-51b4-4f08-9901-b4c5397ee755.png)
В случае если в документе не определяется дата и наименование ДО/ОО, то во вкладке Анализ в колонке Статус выводить "Не хватает атрибутов для анализа документа"
Пример проверки: https://gpn-audit.nemosoft.ru/#/audit/result/642fe0d7fc8b53f8e9951dfe

**Comment by BondarevaEkaterina** [comment]
В случае если в документе не определяется дата и наименование ДО/ОО, то во вкладке Анализ в колонке Статус выводить "Не найдена дата и/или сторона(-ы) для анализа документа"

**Comment by compartia** [comment]
СТАТУС соответсвует модулям пайплайна (фазе процессинга). Атрибуты (или их отсутсвие)  являются результатом работы определенного модуля (продуктом модуля). Поскольку в пределльной ситуации получается комбинаторный взрыв из различных найденно/ненайденных атрибутов, иэтим комбинациям не нужно ставить в соотв. "статус"

На статусы много чего завязано в коде: выборки из базы, обучение, срабатывание анализатора, проч.
Введение еще одного статуса ведет к багам в неожиданных местах.

**Comment by vanyasav** [comment]
Сделано на стороне UI

**Comment by BondarevaEkaterina** [comment]
А мы можем не менять статусы анализа документа в базе, а только на UI в колонке статус выводить "Не найдена дата и/или сторона(-ы) для анализа документа"? Объясняю зачем просим - хотелка пользователя (Заказчика).
