### ISSUE TITLE
Неполное отображение ограничения при переходе по ссылке из графика "Устава" 

### ISSUE THREAD

**Issue by LitJane** [nemoware/gpn-analyse-ui#43]
При переходе по ссылке, например, на "Сделки с имуществом" из графика пороговых сумм Устава, половина текста ограничения остается "за кадром" (см.фото)

![image](https://user-images.githubusercontent.com/55797683/70792845-25434480-1dab-11ea-9727-e6c0dd8c23c9.png)

Хотелось бы чтобы весь текст ограничения был на экране:
![image](https://user-images.githubusercontent.com/55797683/70793138-bfa38800-1dab-11ea-908f-81802a3e4c29.png)

**Comment by IvanKrivosh** [comment]
позиционирование по центру
![image](https://user-images.githubusercontent.com/52923077/70816346-58ec9180-1de0-11ea-8333-df658544331e.png)
