### ISSUE TITLE
Нужна ли форма предпросмотра формы редактирования атрибутов?

### ISSUE THREAD

**Issue by LitJane** [nemoware/gpn-analyse-ui#44]
При переходе из закладки "Анализ" по клику на документ, попадаем в форму предпросмотра формы редактирования атрибутов (или как ее назвать?).
Она визуально ничем не отличается от самой формы редактирования, кроме того что по клику на атрибуты ничего не происходит. Есть ли в ней какой-то сакральный смысл? 
Мне было бы удобнее при переходе из закладки "Анализ" сразу попадать в режим обучения, где сразу можно редактировать атрибуты.

_Нашедшему 3 отличия от меня конфетка_
![image](https://user-images.githubusercontent.com/55797683/70794735-6b9aa280-1daf-11ea-95fc-0e21722a3492.png)
![image](https://user-images.githubusercontent.com/55797683/70794753-748b7400-1daf-11ea-83ac-e1b489d94edf.png)

**Comment by IvanKrivosh** [comment]
Убрать режим просмотра?

**Comment by compartia** [comment]
Это не так уж тривиально
возможно, его следует сделать именно "режимом", а не отдельным экраном.
в режиме же просмотра, попапы атрибутов могут быть просто  рид-онли   - -показывать там значение и название, не позволяя менять.
