### ISSUE TITLE
Предложения по оптимизации закладки "Анализ" в части Уставов :) 

### ISSUE THREAD

**Issue by LitJane** [nemoware/gpn-analyse-ui#45]
- [x] 1. Дату Устава сдвинуть влево, чтобы все даты были друг под другом
- [ ] 2. Добавить Наименование столбца "Ограничения" (А то эта пустая строка несколько смущает)
- [x] 3. Ограничиться одной денежной единицей при указании пороговых сумм
Пример как это могло бы быть ниже:
![image](https://user-images.githubusercontent.com/55797683/70796690-f087bb00-1db3-11ea-961d-18b7d67abeff.png)

**Comment by IvanKrivosh** [comment]
![Безымянный2](https://user-images.githubusercontent.com/52923077/70806630-d0182a80-1dcc-11ea-80a0-62473fc90ea2.png)
п.2. Я не понимать

**Comment by IvanKrivosh** [comment]
п.1 исправлено
п.3 исправлено

**Comment by IvanKrivosh** [comment]
Просьба разъяснить пункт №2. 
П1: 
![image](https://user-images.githubusercontent.com/52923077/70851109-5488ad00-1ea2-11ea-8a20-ce1a09d4fbb3.png)
Дата перенесена, но выглядит очень странно.

**Comment by IvanKrivosh** [comment]
![image](https://user-images.githubusercontent.com/52923077/70851175-0b852880-1ea3-11ea-9757-ca75194c99d4.png)
Даже вот так

**Comment by vanyasav** [comment]
Не актуален.
