### ISSUE TITLE
Показывать развернутый список документов при возврате из формы редактирования атрибутов

### ISSUE THREAD

**Issue by LitJane** [nemoware/gpn-analyse-ui#49]
При возврате из формы редактирования атрибутов в закладку Анализ,  список документов отображается снова в свернутом виде. 
Это будет очень неудобно, если предположить, что в 1ом аудите будет хотя бы 100/200/500/1000 договоров.
 Разумнее возвращаться к списку в развернутом состоянии и , более того, к строке с тем договором, с которого вернулись.

**Comment by IvanKrivosh** [comment]
Документы открываются в новых вкладках.

**Comment by IvanKrivosh** [comment]
Закрываю.

**Comment by SergeyShalaevsky** [comment]
уже не актуален
