### ISSUE TITLE
Редактор атрибутов: если выделять текст справа налево, то диалог не появляется

### ISSUE THREAD

**Issue by compartia** [nemoware/gpn-analyse-ui#50]

**Comment by IvanKrivosh** [comment]
Диалог не появляется, если выделение происходит в атрибуте, которые не имеет дочерних атрибутов или все дочерние атрибуты с признаком once уже отмечены. Проблем не обнаружено.

**Comment by compartia** [comment]
да, перетестил, не воспроизводится
сорри
