### ISSUE TITLE
протокол: редактирование: Пункт повестки дня внутри Пункта повестки дня

### ISSUE THREAD

**Issue by compartia** [nemoware/gpn-analyse-ui#51]
быть не может
<img width="737" alt="Capture d’écran 2019-12-14 à 02 31 53" src="https://user-images.githubusercontent.com/7677437/70823131-2069a980-1e1a-11ea-8e84-1cadc55c7e41.png">

**Comment by compartia** [comment]
<img width="541" alt="Capture d’écran 2019-12-14 à 02 37 07" src="https://user-images.githubusercontent.com/7677437/70823370-ac7bd100-1e1a-11ea-8c56-7e0b1b4205a4.png">

**Comment by IvanKrivosh** [comment]
![image](https://user-images.githubusercontent.com/52923077/70823775-c359fd80-1df1-11ea-8110-3766514d2e05.png)
По атрибутам нет его в списке для выбора

**Comment by IvanKrivosh** [comment]
![image](https://user-images.githubusercontent.com/52923077/70823835-e1bff900-1df1-11ea-9c15-09073565f864.png)
Это выбор для редактирования, т.к. сейчас данный атрибут уже указан он и отображается в списке.
