### ISSUE TITLE
Связанные документы: выбирать документ, а не файл.

### ISSUE THREAD

**Issue by compartia** [nemoware/gpn-analyse-ui#53]
ведь в одном файле может быть много документов
<img width="679" alt="Capture d’écran 2019-12-14 à 13 04 53" src="https://user-images.githubusercontent.com/7677437/70843872-e0cfab80-1e73-11ea-9bc2-f93ed4711b0f.png">

**Comment by IvanKrivosh** [comment]
![Uploading image.png…]()
