### ISSUE TITLE
Изменить формулировку нарушения 

### ISSUE THREAD

**Issue by LitJane** [nemoware/gpn-analyse-ui#57]
"Отсутствует одобрение Совет директоров на **совершение Сделки с имуществом на сумму, превыщающих 50 000 000,00 ₽ и не превыщающих 50 000 000,00 ₽**" изменить на "Отсутствует одобрение Совет директоров на совершение Сделки с имуществом на сумму, превыщающих 50 000 000,00 ₽"

![image](https://user-images.githubusercontent.com/55797683/70902939-e01f4c80-200e-11ea-9ddc-293103d17bfb.png)

**Comment by IvanKrivosh** [comment]
@LitJane, внесены исправления: вместо дубля минимального значения выводится максимальность.

**Comment by IvanKrivosh** [comment]
@LitJane, или суть в том, что бы вообще не показывать максимальный порог, если есть минимальны?

**Comment by LitJane** [comment]
@IvanKrivosh, если добавили максимальную, пусть пока будет так. Это не принципиально.
