### ISSUE TITLE
Нет возможности выбрать предмет договора "Сделки с имуществом"

### ISSUE THREAD

**Issue by LitJane** [nemoware/gpn-analyse-ui#58]
Нет возможности выбрать предмет "Сделки с имуществом" 
И лучше русифицировать предметы :) 
![image](https://user-images.githubusercontent.com/55797683/70907698-93417300-201a-11ea-918d-2caaa99ed243.png)

**Comment by IvanKrivosh** [comment]
![image](https://user-images.githubusercontent.com/52923077/70908326-ff70a680-201b-11ea-93f8-6da0200ccaa5.png)
![image](https://user-images.githubusercontent.com/52923077/70908345-07304b00-201c-11ea-9760-9bd211f0a5c1.png)

**Comment by LitJane** [comment]
@IvanKrivosh, а сделки с имуществом - это разве не RealEstate? 
Подозреваю, что  PropertyDeal все же Сделки с недвижимостью. но это не точно :)
