### ISSUE TITLE
Устав другой копании, один, но наименование не показано

### ISSUE THREAD

**Issue by compartia** [nemoware/gpn-analyse-ui#59]
ДО устава отличается от ДО аудита
expected: наименование показано

<img width="883" alt="Capture d’écran 2019-12-16 à 23 33 08" src="https://user-images.githubusercontent.com/7677437/70919906-aa08b980-205c-11ea-9a8a-3518dc5e9b43.png">

**Comment by IvanKrivosh** [comment]
![image](https://user-images.githubusercontent.com/52923077/71100677-7b0e5700-21c6-11ea-8be3-304207196a42.png)
![image](https://user-images.githubusercontent.com/52923077/71100685-81043800-21c6-11ea-8aef-5b6c2bb1ffcd.png)

**Comment by compartia** [comment]
спасибо, что пофиксил, но ассайно было на меня

**Comment by IvanKrivosh** [comment]
Я видел, но был рядом.
