### ISSUE TITLE
Изменить иконку закладки с аудитом на корпоративную "зажигалку"

### ISSUE THREAD

**Issue by LitJane** [nemoware/gpn-analyse-ui#62]
![image](https://user-images.githubusercontent.com/55797683/70972057-8f156400-20b3-11ea-8263-94d7f6b98e2b.png)
на 
![image](https://user-images.githubusercontent.com/55797683/70972078-976d9f00-20b3-11ea-8b4a-955191b9aeaa.png)

**Comment by compartia** [comment]
<img width="594" alt="Capture d’écran 2019-12-17 à 15 21 06" src="https://user-images.githubusercontent.com/7677437/70973615-f269bb00-20e0-11ea-95de-861d2e5fb56b.png">
<img width="575" alt="Capture d’écran 2019-12-17 à 15 20 12" src="https://user-images.githubusercontent.com/7677437/70973616-f3025180-20e0-11ea-9818-7e8999e4a849.png">
