### ISSUE TITLE
При переходе из списка аудитов открывать "Нарушения"

### ISSUE THREAD

**Issue by LitJane** [nemoware/gpn-analyse-ui#66]
При переходе из списка аудитов на какой-то конкретный аудит - сразу открывать форму с нарушениями.
(Предпочтение от Заказчика)

**Comment by IvanKrivosh** [comment]
Открываем, если есть нарушения, в противном случае - "Анализ"

**Comment by LitJane** [comment]
@IvanKrivosh  пожелание Заказчика (на текущий момент):  если Анализ завершен - открывать закладку Нарушения, даже если Нарушений нет.

Вопрос-пожелание:
Но так как пока, что отсутствие нарушений не означает, что их в принципе нет, может возможно в закладке Нарушений выводить информационное сообщение с таким значком ![image](https://user-images.githubusercontent.com/55797683/70984573-c7c13780-20cb-11ea-94ef-2d4128717330.png) о том, что не все атрибуты были определены -
**"В результате выполненного анализа в документах не были определены все атрибуты"** 
(а сделать это сообщение гиперссылкой на анализ в текущем окне - вообще шикарно было бы!)

**Comment by IvanKrivosh** [comment]
"если по документам были невыявленные атрибуты" - как их определить?

**Comment by IvanKrivosh** [comment]
Для отображения вкладки "Нарушения" анализируется статус аудита: если status in ('Finalizing', 'Done', 'Approved') => показываем.

**Comment by IvanKrivosh** [comment]
@LitJane 
![image](https://user-images.githubusercontent.com/52923077/71019064-bf3c2180-210a-11ea-8e47-3e996b935033.png)
?
