### ISSUE TITLE
Добавить Номер и название статьи в "Нарушениях"

### ISSUE THREAD

**Issue by LitJane** [nemoware/gpn-analyse-ui#67]
В форме "Нарушения", там, где текст ограничения, добавить Номер и название соотвествующей статьи.

**Comment by compartia** [comment]
что такое "статья"?

**Comment by LitJane** [comment]
![image](https://user-images.githubusercontent.com/55797683/70982045-5e3f2a00-20c7-11ea-9704-76616aa37c99.png)

**Comment by compartia** [comment]
@LitJane к 19 нереально, мне кажется.

**Comment by SergeyShalaevsky** [comment]
можно пока брать из заголовков, но не уверен, что это универсальное решение

**Comment by compartia** [comment]
@LitJane Поясни, пожалуйста, почему и зачем им это нужно?

**Comment by LitJane** [comment]
@compartia Это было прописано в ТЗ (и даже более того) и заказчик настаивает на том, что это должно быть выполнено.
Но на текущий момент они согласились хотя бы на Статью (без пунктов).

**Comment by compartia** [comment]
@LitJane вопрос был не "зачем это делать", а "зачем им это нужно"

**Comment by LitJane** [comment]
@compartia я написала тот коммент до того как прочитала твой вопрос. 
Мысли и желания заказчика считывать на расстоянии не умею, обратиться к ним лично возможности пока что нет. Предполагаю, что они всёжюристы и им принципиально видеть статью, к которой относится данное ограничение.
На вчерашней встрече Аналитики  ГПН нам настойчиво напомнили, что здесь должна быть указана статься и пункт, но выслушав доводы согласились хотя бы на Статью.

**Comment by compartia** [comment]
@IvanKrivosh @SergeyShalaevsky вы в финалазере или на ui сможете найти по спанам просто ближайший заголовок? Или нужно что-то из аналайзера?

**Comment by IvanKrivosh** [comment]
@compartia В UI да

**Comment by SergeyShalaevsky** [comment]
> @compartia В UI да

может все же это в нарушение в базе добавлять?

**Comment by IvanKrivosh** [comment]
@SergeyShalaevsky ты передаешь на id элемента, мы считаем предыдущий header и добавим его к тексту.

**Comment by compartia** [comment]
> может все же это в нарушение в базе добавлять?

мне это больше нравится, тк чисто архитектурно UI дожен заниматься форматированием данных, а не формированием оных. (кстати, в редких случаях заголовки могут быть недружественно длинными и их стоит триммать до юзер-френдли длинны)

**Comment by IvanKrivosh** [comment]
Хотя может и в БД лучше хранить.

**Comment by SergeyShalaevsky** [comment]
> @SergeyShalaevsky ты передаешь на id элемента, мы считаем предыдущий header и добавим его к тексту.

я предлагаю вытащить что-то типа Статья <номер статьи> из заголовка и положить это в базу

**Comment by compartia** [comment]
>  что-то типа Статья

там не всегда "Статья", бывает просто номер. Процитируй просто первые, например 200 символов заголовка + эллипсис. До 19 этого вполне достаточно

**Comment by SergeyShalaevsky** [comment]
> там не всегда "Статья", бывает просто номер. Процитируй просто первые, например 200 символов заголовка + эллипсис. До 19 этого вполне достаточно

Жанна, этого достаточно?

**Comment by SergeyShalaevsky** [comment]
> там не всегда "Статья", бывает просто номер. Процитируй просто первые, например 200 символов заголовка + эллипсис. До 19 этого вполне достаточно

если там может быть просто номер или статья номер, то зачем 200 символов? я бы взял 20

**Comment by LitJane** [comment]
@SergeyShalaevsky я думаю для ближайшего показа вполне.
