### ISSUE TITLE
Некорректно выводятся "Основания нарушений" в Нарушениях

### ISSUE THREAD

**Issue by LitJane** [nemoware/gpn-analyse-ui#70]
![image](https://user-images.githubusercontent.com/55797683/70994378-2512b400-20df-11ea-9e44-57617bd83415.png)
Легенда: красное - плохо, желтое - хорошо ))

**Comment by IvanKrivosh** [comment]
@LitJane в UI просто выводится полученные значения атрибутов.

**Comment by LitJane** [comment]
@compartia это к тебе получается?

**Comment by compartia** [comment]
> @compartia это к тебе получается?

@IvanKrivosh Отдаешь?

**Comment by LitJane** [comment]
@compartia 
закрываю и открою другой про определение атрибутов.

**Comment by compartia** [comment]
баги можно просто переименовывать тут

**Comment by LitJane** [comment]
@compartia так баг уже не к ui относится ))) так что всё туда, всё туда
