### ISSUE TITLE
Выводить во всех формах все атрибуты с названиями на русском языке

### ISSUE THREAD

**Issue by LitJane** [nemoware/gpn-analyse-ui#72]
![image](https://user-images.githubusercontent.com/55797683/70996296-83419600-20e3-11ea-83df-fdc0dd43ac13.png)

**Comment by IvanKrivosh** [comment]
@LitJane У меня нет инфы

**Comment by compartia** [comment]
<img width="656" alt="Capture d’écran 2019-12-17 à 21 27 52" src="https://user-images.githubusercontent.com/7677437/70999454-6e312b00-2114-11ea-82c1-94f96f8d1643.png">

**Comment by LitJane** [comment]
ПРОШУ В СРОЧНОМ ПОРЯДКЕ ВСЕ АТРИБУТЫ ПО ВСЕМ ДОКУМЕНТАМ ВЫВОДИТЬ С РУССКИМИ НАИМЕНОВАНИЯМИ (крик души)
**Устав**
 ![image](https://user-images.githubusercontent.com/55797683/71091325-f1ef2400-21b5-11ea-86ad-b022dae150af.png)
![image](https://user-images.githubusercontent.com/55797683/71091352-ff0c1300-21b5-11ea-9733-5d0cd007afaa.png)
![image](https://user-images.githubusercontent.com/55797683/71091428-25ca4980-21b6-11ea-98d8-4030756907eb.png)

**Протокол**
![image](https://user-images.githubusercontent.com/55797683/71091519-4f837080-21b6-11ea-9cc8-c8963812fd30.png)

Спасибо!

**Comment by IvanKrivosh** [comment]
@compartia 
![image](https://user-images.githubusercontent.com/52923077/71092182-d38a2800-21b7-11ea-824e-21c2919dca25.png)
В каких случаях value русский текст, а в каких значение из справочника?

**Comment by compartia** [comment]
@IvanKrivosh это очень устаревший пример json от 4 дек.
в последних версиях в value всегда только код.
На всякий случай, еще раз ссылка на знакомый тебе справочник: https://github.com/nemoware/analyser/blob/723b2275d469f20df58b8ae1f728cf0dd91cb735/analyser/structures.py#L49

**Comment by IvanKrivosh** [comment]
@compartia, или структурный уровень стал справочником?

**Comment by IvanKrivosh** [comment]
@compartia, спасибо. Сделаем справочником.

**Comment by IvanKrivosh** [comment]
1. Атрибут "структурный уровень" -> справочник:
![image](https://user-images.githubusercontent.com/52923077/71096658-c1ac8300-21bf-11ea-91a7-523e2d39f977.png)
2. В уставе для типов атрибутов, которые не выбирается значение, поле "Значение" скрывается:
![image](https://user-images.githubusercontent.com/52923077/71096973-4e574100-21c0-11ea-9bbc-67330c7d2d81.png)

**Comment by compartia** [comment]
![image](https://user-images.githubusercontent.com/7677437/71164420-f8e76680-2289-11ea-8534-2f93378ed52c.png)
