### ISSUE TITLE
Устав: невозможно редактировать дату

### ISSUE THREAD

**Issue by compartia** [nemoware/gpn-analyse-ui#75]
<img width="929" alt="Capture d’écran 2019-12-18 à 02 15 18" src="https://user-images.githubusercontent.com/7677437/71022862-78ffb600-213c-11ea-865e-70c7f9512e46.png">

**Comment by IvanKrivosh** [comment]
![image](https://user-images.githubusercontent.com/52923077/71089297-991d8c80-21b1-11ea-9f9b-b62ffdd3c553.png)
