### ISSUE TITLE
phantom labels

### ISSUE THREAD

**Issue by compartia** [nemoware/gpn-analyse-ui#8]
Chrome, Opera:
set focus to an input field -> label is nearly transparent
expected: label is visible with healthy human eye 

<img width="496" alt="Capture d’écran 2019-09-30 à 18 05 19" src="https://user-images.githubusercontent.com/7677437/65870333-94b1b680-e3ae-11e9-927e-06d98e2ee0c0.png">

 
<img width="497" alt="Capture d’écran 2019-09-30 à 18 16 45" src="https://user-images.githubusercontent.com/7677437/65871114-574e2880-e3b0-11e9-9425-64b2e49f089f.png">

**Comment by compartia** [comment]
#5

**Comment by IvanKrivosh** [comment]
problems with default themes gpn.settings.themes.blue and gpn.settings.themes.light:
![theme_ligth](https://user-images.githubusercontent.com/52923077/65877630-d2094a80-e394-11e9-83a2-11f4b51fd32d.png)

gpn.settings.themes.nature and gpn.settings.themes.dark are view well:
![theme_natural](https://user-images.githubusercontent.com/52923077/65877566-ad14d780-e394-11e9-8faa-c0dca4879e2f.png)
![theme_dark](https://user-images.githubusercontent.com/52923077/65877570-aede9b00-e394-11e9-8281-c9ac26b0c2e6.png)

**Comment by compartia** [comment]
@IvanKrivosh  настройки тем следует искоренить, -- они достались нам из проекта-бутстрапа. Оставим лишь "светлую"

**Comment by IvanKrivosh** [comment]
В любом случае, светлую тему нужно напильником пройти, т.к. mat элементы на ней не очень выглядят
